// Extracts the SVG path data of the Material Symbols (Rounded, weight 400)
// icons the UI uses into src/lib/icons.generated.ts — only these ship.
// Usage: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const root = path.dirname(require.resolve("@material-symbols/svg-400/package.json"));
const names = readFileSync(new URL("./icons.txt", import.meta.url), "utf8")
  .split(/\s+/)
  .map((s) => s.trim())
  .filter(Boolean)
  .sort();

const extract = (file) => {
  const svg = readFileSync(path.join(root, "rounded", file), "utf8");
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length) throw new Error(`No path in ${file}`);
  return paths.join(" ");
};

const entries = [...new Set(names)].map((name) => {
  const outline = extract(`${name}.svg`);
  let fill = outline;
  try {
    fill = extract(`${name}-fill.svg`);
  } catch {
    /* some icons have no filled variant */
  }
  return `  ${JSON.stringify(name)}: [${JSON.stringify(outline)}, ${JSON.stringify(fill)}],`;
});

writeFileSync(
  new URL("../src/lib/icons.generated.ts", import.meta.url),
  `// Generated by scripts/generate-icons.mjs from @material-symbols/svg-400 (Apache-2.0). Do not edit.\n` +
    `// [outlined path, filled path] in a "0 -960 960 960" viewBox.\n` +
    `export const ICONS = {\n${entries.join("\n")}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`,
);
console.log(`Wrote ${entries.length} icons`);
