// Generates Material 3 (2025 "Expressive" spec) colour roles as CSS custom
// properties for light and dark themes from a single seed colour.
// Usage: node scripts/generate-theme.mjs [seedHex] [scheme] > src/styles/theme.css
import {
  Blend,
  Hct,
  MaterialDynamicColors,
  TonalPalette,
  SchemeExpressive,
  SchemeTonalSpot,
  SchemeVibrant,
  argbFromHex,
  hexFromArgb,
} from "@material/material-color-utilities";

const seed = process.argv[2] ?? "#6750FF";
const kind = process.argv[3] ?? "vibrant";
const Scheme = { expressive: SchemeExpressive, vibrant: SchemeVibrant, tonalspot: SchemeTonalSpot }[kind];

const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer", "inversePrimary",
  "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "secondaryFixed", "secondaryFixedDim", "onSecondaryFixed", "onSecondaryFixedVariant",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
  "error", "onError", "errorContainer", "onErrorContainer",
  "background", "onBackground", "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceDim", "surfaceBright", "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest", "inverseSurface", "inverseOnSurface",
  "outline", "outlineVariant", "shadow", "scrim", "surfaceTint",
];

const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

// Custom semantic colours (M3 "custom colors"), harmonized toward the seed.
const CUSTOM = { success: "#1E8E3E", warning: "#E8A317" };

function customBlock(isDark) {
  return Object.entries(CUSTOM)
    .flatMap(([name, hex]) => {
      const palette = TonalPalette.fromInt(Blend.harmonize(argbFromHex(hex), argbFromHex(seed)));
      const [c, on, container, onContainer] = isDark ? [80, 20, 30, 90] : [40, 100, 90, 10];
      return [
        `  --md-${name}: ${hexFromArgb(palette.tone(c))};`,
        `  --md-on-${name}: ${hexFromArgb(palette.tone(on))};`,
        `  --md-${name}-container: ${hexFromArgb(palette.tone(container))};`,
        `  --md-on-${name}-container: ${hexFromArgb(palette.tone(onContainer))};`,
      ];
    })
    .join("\n");
}

/*
 * The 2025 spec keeps primary/tertiary containers bright (tone ~70) in dark
 * mode. Our layouts put primary-coloured text and large hero surfaces on those
 * containers, which reads as glaring slabs with low-contrast text on a dark
 * page. In dark mode we therefore use the same vibrant palettes at the classic
 * container tones (30 surface / 90 text), which keeps the hues but restores
 * readable contrast everywhere.
 */
const DARK_CONTAINER_OVERRIDES = {
  primaryContainer: ["primaryPalette", 30],
  onPrimaryContainer: ["primaryPalette", 90],
  tertiaryContainer: ["tertiaryPalette", 30],
  onTertiaryContainer: ["tertiaryPalette", 90],
};

function block(isDark) {
  const scheme = new Scheme(Hct.fromInt(argbFromHex(seed)), isDark, 0, "2025");
  const value = (role) => {
    const override = isDark ? DARK_CONTAINER_OVERRIDES[role] : undefined;
    return override ? scheme[override[0]].tone(override[1]) : MaterialDynamicColors[role].getArgb(scheme);
  };
  const roles = ROLES.map((role) => `  --md-${kebab(role)}: ${hexFromArgb(value(role))};`).join("\n");
  return `${roles}\n${customBlock(isDark)}`;
}

const light = block(false);
const dark = block(true);
console.log(`/* Generated by scripts/generate-theme.mjs — seed ${seed}, scheme ${kind}, spec 2025. Do not edit by hand. */
:root,
:root[data-theme="light"] {
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replace(/^/gm, "  ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}`);
